#main_title = "Phanes Main Menu"
main_title = "Phanes Hauptmenü"
#view_tasks_title = "Phanes View Tasks Menu"
view_tasks_title = "Phanes Aufgabenübersicht"
#view_task_menu = "View Tasks Menu"
view_task_menu = "Aufgabenübersicht anzeigen"
#manage_task = "Manage Task Menu"
manage_task = "Aufgabenverwaltung anzeigen"
#manage_categories = "Manage Categories"
manage_categories = "Kategorieverwaltung anzeigen"

#view_all_open = "View all open tasks"
view_all_open = "Alle ausstehenden Aufgaben anzeigen"
#view_all_in_progress = "View all in-progress tasks"
view_all_in_progress = "Alle laufenden Aufgaben anzeigen"
#view_all_closed = "View all closed tasks"
view_all_closed = "Alle abgeschlossenen Aufgaben anzeigen"
#view_task_info = "View task information"
view_task_info = "Aufgabeninformationen anzeigen"

#open_tasks = "Open Tasks"
open_tasks = "Ausstehende Aufgaben"
#inprogress_tasks = "In-progress Tasks"
inprogress_tasks = "Laufende Aufgaben"
#closed_tasks = "Closed Tasks"
closed_tasks = "Abgeschlossene Aufgaben"

#return_menu = "Return to main menu"
return_menu = "Zurück zum Hauptmenü"
#return = "Return"
return = "Zurück"
#quit = "Quit"
quit = "Beenden"
