#main_title = "Phanes Main Menu"
main_title = "Phanes Hauptmenü"
#view_tasks_title = "Phanes View Tasks Menu"
view_tasks_title = "Phanes Aufgabenübersicht"
#view_task_menu = "View Tasks Menu"
view_task_menu = "Aufgabenübersicht anzeigen"
#manage_task = "Manage Task Menu"
manage_task = "Aufgabenverwaltung anzeigen"
#manage_categories = "Manage Categories"
manage_categories = "Kategorieverwaltung anzeigen"

#view_all_open = "View all open tasks"
view_all_open = "Alle ausstehenden Aufgaben anzeigen"
#view_all_in_progress = "View all in-progress tasks"
view_all_in_progress = "Alle laufenden Aufgaben anzeigen"
#view_all_closed = "View all closed tasks"
view_all_closed = "Alle abgeschlossenen Aufgaben anzeigen"
#view_task_info = "View task information"
view_task_info = "Aufgabeninformationen anzeigen"

#open_tasks = "Open Tasks"
open_tasks = "Ausstehende Aufgaben"
#inprogress_tasks = "In-progress Tasks"
inprogress_tasks = "Laufende Aufgaben"
#closed_tasks = "Closed Tasks"
closed_tasks = "Abgeschlossene Aufgaben"

#add_task = "Add a task"
add_task = "Neue Aufgabe"
#del_task = "Delete a task"
del_task = "Aufgabe löschen"
#move_in_prog = "Move task to in-progress"
move_in_prog = "Aufabe als laufend markieren"
#move_to_closed = "Move task to closed"
move_to_closed = "Aufgabe schließen"
#assign_task_cat = "Assign task a category"
assign_task_cat = "Aufgabe eine Kategorie zuweisen"

#title = "Title:"
title = "Titel:"
#description = "Description:"
description = "Beschreibung:"
#category = "Category:"
category = "Kategorie:"
#status = "Status:"
status = "Status:"

#select_task = "Select a task"
select_task = "Aufgabe auswählen"
#select_cat = "Select a category"
select_cat = "Kategorie auswählen"
#select = "Select"
select = "Auswählen"

#add_cat = "Add a category"
add_cat = "Kategorie hinzufügen"
#del_cat = "Delete a category"
del_cat = "Kategorie löschen"
#list_cat = "List Categories"
list_cat = "Kategorien anzeigen"

#submit = "Submit"
submit = "Bestätigen"
#canel = "Cancel"
canel = "Abbrechen""

#success = "Successful Operation Complete"
success = "Aktion erfolgreich durchgeführt."
#failure = "Operation failed to complete"
failure = "Durchführung der Aktion fehlgeschlagen."

#db_path = "Database path"
db_path = "Datenbankpfad"
#get_db_path = "Enter path to database"
get_db_path = "Pfad zur Datenbank eingeben"
#new = "new"
new = "neu"
#new_db = "New database"
new_db = "Neue Datenbank"
#get_new_db = "Enter path to new database"
get_new_db = "Pfad zur neuen Datenbank eingeben"
#existing_db = "Existing database"
existing_db = "Bestehende Datenbank"
#get_existing_db = "Enter path to an existing database"
get_existing_db = "Pfad zu einer bestehenden Datenbank eingeben"

#return_menu = "Return to main menu"
return_menu = "Zurück zum Hauptmenü"
#return = "Return"
return = "Zurück"
#quit = "Quit"
quit = "Beenden"
