main_title = "Phanes Main Menu"
view_tasks_title = "Phanes View Tasks Menu"
view_task_menu = "View Tasks Menu"
manage_task = "Manage Task Menu"
manage_categories = "Manage Categories"
view_all_open = "View all open tasks"
view_all_in_progress = "View all in-progress tasks"
view_all_closed = "View all closed tasks"
view_task_info = "View task information"
return_menu = "Return to main menu"
return = "Return"
quit = "Quit"
